version: '3.7'

services:

  caddy:
    container_name: caddy
    image: caddy:2-alpine
    network_mode: host
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data:rw
      - caddy-config:/config:rw
    environment:
      - SEARXNG_HOSTNAME=${SEARXNG_HOSTNAME:-http://localhost:80}
      - SEARXNG_TLS=${LETSENCRYPT_EMAIL:-internal}
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE

  redis:
    container_name: redis
    image: "redis:alpine"
    command: redis-server --save "" --appendonly "no"
    networks:
      - searxng
    tmpfs:
      - /var/lib/redis
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE

  searxng:
    container_name: searxng
    image: searxng/searxng:latest
    networks:
      - searxng
    ports:
     - "127.0.0.1:8080:8080"
    volumes:
      - ./searxng:/etc/searxng:rw
      - ./donate.md:/usr/local/searxng/searx/infopage/en/donate.md
      - ./about.md:/usr/local/searxng/searx/infopage/en/about.md
      - ./search-syntax.md:/usr/local/searxng/searx/infopage/en/search-syntax.md
      - ./sitemap.xml:/usr/local/searxng/searx/infopage/en/sitemap.xml
      - ./templates/simple/preferences.html:/usr/local/searxng/searx/templates/simple/preferences.html
      - ./templates/simple/index.html:/usr/local/searxng/searx/templates/simple/index.html
      - ./templates/simple/base.html:/usr/local/searxng/searx/templates/simple/base.html
      - ./templates/simple/index.less:/usr/local/searxng/searx/static/themes/simple/src/less/index.less
      - ./templates/simple/css/searxng.min.css:/usr/local/searxng/searx/static/themes/simple/css/searxng.min.css
      - ./templates/simple/css/searxng-rtl.min.css:/usr/local/searxng/searx/static/themes/simple/css/searxng-rtl.min.css
      - ./templates/simple/css/searxng.min.css.map:/usr/local/searxng/searx/static/themes/simple/css/searxng.min.css.map
      - ./templates/simple/css/searxng-rtl.min.css.map:/usr/local/searxng/searx/static/themes/simple/css/searxng-rtl.min.css.map
      - ./static/themes/simple/img/busqueda.svg:/usr/local/searxng/searx/templates/simple/searxng-wordmark.min.svg
      - ./static/themes/simple/img/logo.png:/usr/local/searxng/searx/static/themes/simple/img/searxng.png
      - ./static/themes/simple/img/favicon.png:/usr/local/searxng/searx/static/themes/simple/img/favicon.png
      - ./static/themes/simple/img/favicon.svg:/usr/local/searxng/searx/static/themes/simple/img/favicon.svg
    environment:
      - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:-localhost}/
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
networks:
  searxng:
    ipam:
      driver: default

volumes:
  caddy-data:
  caddy-config:
